FROM google/dart:2.8 AS dartimage

COPY app/ /app/

# Compiling the Dart application that manages this action
RUN cd /app \
    && pub get \
    && dart2native /app/bin/main.dart -o /app/dart_package_analyzer

# Using a lighter parent image to build the final image
FROM bitnami/minideb:latest

# Copying only the executable
COPY --from=dartimage /app/dart_package_analyzer /dart_package_analyzer

ENV PATH /flutter/bin/cache/dart-sdk/bin:/root/.pub-cache/bin:/flutter/bin:$PATH

RUN install_packages git unzip curl ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Installing Flutter
RUN git clone -b stable --depth 1 https://github.com/flutter/flutter.git /flutter \
    && flutter --version

# Installing and activating pana
RUN flutter pub global activate pana
