FROM google/dart:2.6-dev as dartimage

COPY app/ /app/

# Compiling the Dart application that manages this action
RUN cd /app \
    && pub get \
    && dart2native /app/bin/main.dart -o /app/dart_package_analyzer

# Using a lighter parent image to build the final image
FROM bitnami/minideb

# Copying only the executable
COPY --from=dartimage /app/dart_package_analyzer /dart_package_analyzer

# Installing Flutter
RUN apt-get update \
    && apt-get -y install git unzip curl \
    && git clone -b stable --depth 1 https://github.com/flutter/flutter.git /flutter \
    && /flutter/bin/flutter --version